[project]
name = "comfyui-remove-background"
description = "Remove background scenery from an image of a person. The output options are RGB, RGBA and Alpha Channel only."
version = "1.1.0"
license = "Apache License, Version 2.0"
dependencies = ["onnxruntime", "rembg"]

[project.urls]
Repository = "https://github.com/Sean-Bradley/ComfyUI-Remove-Background"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/Sean-Bradley/ComfyUI-Remove-Background/wiki"
"Bug Tracker" = "https://github.com/Sean-Bradley/ComfyUI-Remove-Background/issues"

[tool.comfy]
PublisherId = "sbcode"
DisplayName = "ComfyUI Remove Background"
Icon = "https://avatars.githubusercontent.com/u/59069470"